name: diabetes-prediction-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - mlflow==2.19.0
      - scikit-learn==1.3.2
      - pandas==2.0.3
      - numpy==1.24.3
      - matplotlib==3.7.2
      - seaborn==0.12.2
      - dagshub==0.3.0